#### 整合freemarker
spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path:
      - classpath:/templates
  application:
    name: app-zdd-portal-web
  ###数据库相关连接
#  datasource:
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://204.44.83.252:3306/zdd_weixin?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&&serverTimezone=UTC

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://204.44.83.252:8080/eureka

server:
  port: 8100
