logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
      - appId: wx2d006a1de02c6767 #（一个公众号的appid）
        secret: a429b711a15c510c29e33a20c301d9ce #（公众号的appsecret）
        token: zdd #（接口配置里的Token值）

server:
  port: 8200

eureka:
  client:
    service-url:
#      defaultZone: http://204.44.83.252:8080/eureka
      defaultZone: http://155.94.170.236:8100/eureka

zdd:
  weixin:
    registration:
       code:
       ###微信注册码消息
        message:  您的注册码为:%s，欢迎您注册！！！
    ###默认提示消息
    default:
      registration:
        code:
          message: 您的消息，我们已经收到,会及时回复给您的!

spring:
  application:
    name: app-zdd-weixin
  redis:
    host: 155.94.170.236
    port: 6379
    password: zdd1234
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  ###数据库相关连接
  datasource:
    username: root
    password: yuruiqi666
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://155.94.170.236/zdd_weixin?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&&serverTimezone=UTC


#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

  