###服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-zdd-weixin
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka


####swagger相关配置
swagger:
  base-package: com.zdd.weixin.service
  title: SpringCloud2.x构建微服务电商项目-微信服务接口
  description: 该项目基于SpringCloud2.x构建微服务电商项目
  version: 1.1
  terms-of-service-url: www.zdd.com
  contact:
    name: zdd
    email: 123@qq.com