
###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)  
#spring:
#    application:
#        name: app-zdd-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
#           defaultZone: http://204.44.83.252:8080/eureka
           defaultZone: http://155.94.170.236:8100/eureka

spring:
  application:
    name: app-zdd-member
  redis:
    host: 155.94.170.236
    port: 6379
    password: zdd1234
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  ###数据库相关连接
  datasource:
    username: root
    password: yuruiqi666
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://155.94.170.236:3306/zdd_member?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&&serverTimezone=UTC

####打印MyBatias日志    
logging:
  level:
  ### 开发环境使用DEBUG 生产环境info或者error
   com.zdd.member.mapper: DEBUG

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
