
###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)  
#spring:
#    application:
#        name: app-zdd-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://204.44.83.252:8080/eureka
spring:
  application:
    name: app-zdd-member

####打印MyBatias日志    
logging:
  level:
  ### 开发环境使用DEBUG 生产环境info或者error
   com.zdd.member.mapper: DEBUG
  